version: "3.9"
services:
  web:
    container_name: shoes-app-frontend
    image: shoes-app-frontend-image
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: shoes-app-backend
    container_name: shoes-app-backend-image
    build: ./backend
    command: json-server --watch /data/db.json --port 3004 --host 0.0.0.0
    ports:
      - "3004:3004"
    